
# ---------------------------------------------------------------------------
# Sourced instance catalog
# ---------------------------------------------------------------------------
# Every instance below is a REAL published case. Citations are author-year-venue
# only; no page numbers or DOIs are asserted beyond what is certain.
# Inferences beyond the cited source are marked INFERENCE in notes.

from tpc_engine import TPCInstance


def build_catalog() -> list[TPCInstance]:
    """Sourced instances for 2026-09-25 buildout. Freshness 1.0 reserved for 2026 locks."""
    return [
        TPCInstance(
            id="LASSO_ZERO_NO_EFFECT",
            realm="statistics",
            name="LASSO-zeroed coefficients reported as 'no effect'",
            source="Tibshirani 1996, J. Royal Stat. Soc. B (LASSO); Lee, Sun, Sun & Taylor 2016, Ann. Appl. Stat. (exact post-selection inference)",
            source_date="1996/2016",
            omission_kind="regularization",
            omitted="Coefficients shrunk to exactly zero by L1 penalty",
            zero_treatment="Zeroed predictors reported as having 'no effect'; naive CIs computed post-selection as if the model were pre-specified",
            known_fact=("LASSO sets coefficients exactly to zero. Naive confidence intervals after "
                        "selection are invalid -- the entire post-selection inference literature (Lee et al. 2016) "
                        "exists because treating the selected model as pre-specified injects false certainty."),
            gap_statement=("The zero is an omission by regularization, not a measurement of no effect. "
                           "Downstream 'X has no effect' claims treat it as measured."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.75, freshness=0.45, uniqueness=0.70, g2_strength=0.90, duality_clarity=0.85,
            notes="PRIMARY CANDIDATE. PPC-dual: adding a phantom confounder absorbing the signal would be the PPC version of the same privilege.",
        ),
        TPCInstance(
            id="STEPWISE_COVARIATE_DROP",
            realm="statistics",
            name="Stepwise/AIC covariate dropping without selection uncertainty",
            source="Simmons, Nelson & Simonsohn 2011, Psych. Science (researcher degrees of freedom); Harrell 2015, Regression Modeling Strategies, Springer",
            source_date="2011/2015",
            omission_kind="dropping",
            omitted="Covariates dropped by stepwise/AIC selection",
            zero_treatment="Final model reported with standard errors as if the dropped covariates were known-absent; p-values computed on the selected model",
            known_fact=("Researcher degrees of freedom include covariate dropping (Simmons et al. 2011). "
                        "Harrell documents that stepwise selection invalidates reported p-values and CIs."),
            gap_statement=("Dropped covariates are treated as measured-zero rather than as unmeasured; "
                           "the surviving model's certainty is privileged by the omission."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.80, freshness=0.40, uniqueness=0.65, g2_strength=0.85, duality_clarity=0.80,
            notes="INFERENCE: the 'treated as measured-zero' reading of stepwise reporting is the TPC framing; the invalidity of post-selection p-values is sourced.",
        ),
        TPCInstance(
            id="ABSENCE_OF_EVIDENCE",
            realm="medicine",
            name="Non-significant results reported as 'no effect'",
            source="Altman & Bland 1995, BMJ ('Absence of evidence is not evidence of absence')",
            source_date="1995",
            omission_kind="dropping",
            omitted="Unmeasured effect sizes in underpowered studies (the effect not detected)",
            zero_treatment="'No significant difference' written and cited as 'no effect' -- the undetected effect enters the literature as zero",
            known_fact=("Altman & Bland 1995: a non-significant result does not demonstrate no effect; "
                        "absence of evidence is not evidence of absence. The misreading is endemic in medical reporting."),
            gap_statement=("The omission (failure to detect) is converted into a positive zero-claim downstream; "
                           "meta-analyses and guidelines inherit the false zero."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.85, freshness=0.30, uniqueness=0.60, g2_strength=0.80, duality_clarity=0.70,
            notes="Boundary case: the 'omission' is by underpowered design rather than explicit truncation; G1 holds weakly (dropping of the undetected). Kept as PENALIZED-leaning; engine decides.",
        ),
        TPCInstance(
            id="GWAS_PC_DROP",
            realm="genomics",
            name="Dropped principal components in GWAS stratification correction",
            source="Price et al. 2006, Nature Genetics (EIGENSTRAT)",
            source_date="2006",
            omission_kind="truncation",
            omitted="Higher principal components beyond the retained top-k",
            zero_treatment="Association statistics computed as if the dropped PCs contain no population structure (their contribution set to zero)",
            known_fact=("EIGENSTRAT corrects stratification with top PCs. Residual stratification from unmodeled structure "
                        "is a documented concern in GWAS."),
            gap_statement=("The dropped PCs are treated as measured-empty of structure; any residual stratification "
                           "is invisible to the corrected statistics, privileging the retained-k model."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.65, freshness=0.35, uniqueness=0.68, g2_strength=0.70, duality_clarity=0.75,
            notes="INFERENCE: Price et al. establish the top-k method; the 'dropped PCs as measured-empty' reading is the TPC framing.",
        ),
        TPCInstance(
            id="PRS_THRESHOLD_ZERO",
            realm="genomics",
            name="Polygenic-score clumping+thresholding zeroes sub-threshold SNPs",
            source="Choi, Mak & O'Reilly 2020, Nature Protocols (PRS tutorial)",
            source_date="2020",
            omission_kind="thresholding",
            omitted="All SNPs below the p-value threshold (effects set to exactly 0 in the score)",
            zero_treatment="Risk scores summed over retained SNPs only; sub-threshold SNP effects enter clinical models as zero",
            known_fact=("Standard PRS 'clumping and thresholding' discards sub-threshold variants. "
                        "Choi et al. 2020 document the procedure as the field's workhorse."),
            gap_statement=("Millions of small effects are zeroed by threshold, then the score is used as if the "
                           "zeroing were a measurement of no effect -- privileging the retained-SNP model in clinical prediction."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.80, freshness=0.55, uniqueness=0.72, g2_strength=0.85, duality_clarity=0.80,
            notes="",
        ),
        TPCInstance(
            id="DICHOTOMIZATION",
            realm="epidemiology",
            name="Dichotomizing continuous predictors (median splits)",
            source="Royston, Altman & Sauerbrei 2006, Statistics in Medicine ('Dichotomizing continuous predictors... a bad idea')",
            source_date="2006",
            omission_kind="discretization",
            omitted="Within-group variation of the continuous predictor (collapsed to 0/1)",
            zero_treatment="Group contrasts reported as if all members of a group share the group value; within-group gradients treated as zero",
            known_fact=("Royston et al. 2006 demonstrate dichotomization loses power and biases estimates; "
                        "it remains widespread in medical reporting."),
            gap_statement=("Discretization zeroes the within-bin gradient, then the analysis proceeds as if the "
                           "gradient were measured-absent -- a truncation-privilege on the binned model."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.70, freshness=0.35, uniqueness=0.66, g2_strength=0.75, duality_clarity=0.65,
            notes="",
        ),
        TPCInstance(
            id="ZERO_IMPUTATION",
            realm="statistics",
            name="Zero/mean imputation of missing values treated as observed",
            source="Little & Rubin, Statistical Analysis with Missing Data, Wiley (3rd ed. 2019)",
            source_date="2019",
            omission_kind="imputation",
            omitted="The unobserved values (replaced by 0 or the mean)",
            zero_treatment="Imputed values enter regressions, variances, and CIs as if measured; standard errors shrink as if n were complete",
            known_fact=("Little & Rubin document that single imputation (including mean/zero substitution) "
                        "understates uncertainty; the imputed values are not data."),
            gap_statement=("The omission (missingness) is papered with a constant, then the constant is "
                           "treated as a measurement -- textbook truncation-privilege."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.70, freshness=0.40, uniqueness=0.62, g2_strength=0.90, duality_clarity=0.70,
            notes="",
        ),
        TPCInstance(
            id="FIXED_EFFECT_TAU_ZERO",
            realm="meta-analysis",
            name="Fixed-effect meta-analysis sets between-study variance to zero",
            source="Borenstein, Hedges, Higgins & Rothstein 2009, Introduction to Meta-Analysis, Wiley",
            source_date="2009",
            omission_kind="dropping",
            omitted="Between-study heterogeneity variance (tau-squared), fixed at 0 by model choice",
            zero_treatment="Pooled estimate and CI computed with tau^2 = 0 exactly; heterogeneity treated as measured-absent",
            known_fact=("The fixed-effect model assumes one true effect (tau^2 = 0). Borenstein et al. document "
                        "that applying it under heterogeneity understates uncertainty."),
            gap_statement=("A modeling assumption (tau^2 = 0) is consumed downstream as a measurement of homogeneity; "
                           "the pooled CI is privileged by the omission."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.75, freshness=0.35, uniqueness=0.64, g2_strength=0.95, duality_clarity=0.75,
            notes="Strongest G2 in catalog: the zero is literally in the equations.",
        ),
        TPCInstance(
            id="FILE_DRAWER",
            realm="meta-science",
            name="File-drawer problem: unpublished nulls omitted from the literature",
            source="Rosenthal 1979, Psychological Bulletin (the file drawer problem)",
            source_date="1979",
            omission_kind="dropping",
            omitted="Unpublished null-result studies (missing from meta-analytic distributions)",
            zero_treatment="Published set treated as the whole evidence distribution; missing studies effectively zero-weighted as if confirmed-absent",
            known_fact=("Rosenthal 1979 named the file-drawer problem: null results stay unpublished, "
                        "biasing the published record. Publication bias is among the most replicated meta-scientific findings."),
            gap_statement=("The literature omits nulls, then meta-analysis treats the truncated distribution as complete -- "
                           "the omission privileges every published positive."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.90, freshness=0.25, uniqueness=0.58, g2_strength=0.70, duality_clarity=0.60,
            notes="INFERENCE: the 'zero-weighted as confirmed-absent' reading is the TPC framing; publication bias itself is sourced.",
        ),
        TPCInstance(
            id="EFT_OPERATOR_DROP",
            realm="physics",
            name="EFT fits truncate at dimension-6; dim-8 Wilson coefficients set to zero",
            source="Burgess 2007, Ann. Rev. Nucl. Part. Sci. (EFT introduction)",
            source_date="2007",
            omission_kind="truncation",
            omitted="Higher-dimension operators (dim-8+) in effective field theory fits",
            zero_treatment="Global fits quote bounds on dim-6 coefficients with dim-8+ set to zero exactly, as if measured-vanishing",
            known_fact=("EFT organizes physics as a tower of operators suppressed by powers of (E/Lambda). "
                        "Truncation at dim-6 is standard practice; Burgess 2007 reviews the framework."),
            gap_statement=("The truncated tower is treated as complete; quoted bounds inherit certainty from "
                           "coefficients that were never measured -- truncation-privilege on the dim-6 fit."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.55, freshness=0.35, uniqueness=0.70, g2_strength=0.75, duality_clarity=0.85,
            notes="INFERENCE: Burgess establishes the EFT tower; the 'bounds quoted as if complete' reading is the TPC framing of standard fitting practice.",
        ),
        TPCInstance(
            id="LOSSY_CLIMATE",
            realm="climate",
            name="Lossy-compressed climate simulation data treated as exact downstream",
            source="Baker et al. 2016, Geoscientific Model Development (lossy compression on climate ensembles)",
            source_date="2016",
            omission_kind="truncation",
            omitted="Sub-threshold floating-point detail discarded by lossy compressors",
            zero_treatment="Compressed fields used in ensemble statistics as if bit-exact; compression error treated as zero in downstream analyses",
            known_fact=("Baker et al. 2016 evaluate lossy compression on climate simulation data; the paper exists "
                        "precisely because treating compressed data as exact needed validation."),
            gap_statement=("The compressor truncates information; downstream ensemble means/CIs proceed as if "
                           "nothing was discarded -- the discarded detail is privileged-as-zero."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.50, freshness=0.45, uniqueness=0.68, g2_strength=0.65, duality_clarity=0.60,
            notes="",
        ),
        TPCInstance(
            id="LSA_TRUNCATED_SVD",
            realm="NLP",
            name="LSA truncated SVD: document similarity computed as if exact",
            source="Deerwester et al. 1990, J. American Soc. Information Science (latent semantic analysis)",
            source_date="1990",
            omission_kind="truncation",
            omitted="Discarded singular values/vectors beyond rank k",
            zero_treatment="Cosine similarities in k-space reported and ranked as if the truncation introduced no error",
            known_fact=("LSA truncates the term-document SVD to rank k (Deerwester et al. 1990); the method's "
                        "value comes from the truncation, which is also its unadmitted error source."),
            gap_statement=("The rank-k approximation is consumed as the semantic space itself; the discarded "
                           "spectrum is treated as measured-zero rather than as approximation error."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.40, freshness=0.25, uniqueness=0.60, g2_strength=0.70, duality_clarity=0.65,
            notes="",
        ),
        TPCInstance(
            id="EARLY_STOPPING",
            realm="ML",
            name="Early stopping treated as convergence",
            source="Prechelt 1998, Neural Networks (early stopping -- but when?); Sjoberg & Ljung 1995 (early stopping as regularization)",
            source_date="1998",
            omission_kind="truncation",
            omitted="The remaining optimization trajectory (un-taken gradient steps)",
            zero_treatment="Stopped weights reported and deployed as 'the trained model'; the truncation of training treated as if convergence were measured",
            known_fact=("Early stopping is formally equivalent to L2 regularization (Sjoberg & Ljung 1995); "
                        "Prechelt 1998 studies stopping criteria. The stopped point is not the optimum."),
            gap_statement=("Training is truncated, then the truncated weights are treated as the solution -- "
                           "the un-taken trajectory's contribution is zeroed by fiat."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.45, freshness=0.35, uniqueness=0.66, g2_strength=0.60, duality_clarity=0.70,
            notes="INFERENCE: the equivalence results are sourced; the 'treated as converged' reading is the TPC framing.",
        ),
        TPCInstance(
            id="TIDAL_CONSTITUENT_DROP",
            realm="oceanography",
            name="Tidal harmonic analysis drops unfitted constituents",
            source="Codiga 2011, URI/GSO Technical Report (UTide: Unified Tidal Analysis and Prediction)",
            source_date="2011",
            omission_kind="truncation",
            omitted="Tidal constituents not in the fitted set (shallow-water and long-period residuals)",
            zero_treatment="Predictions generated from fitted constituents only; unfitted energy treated as zero in forecast error budgets",
            known_fact=("UTide fits a selected constituent set (Codiga 2011). Any harmonic analysis leaves "
                        "unfitted constituents in the residual."),
            gap_statement=("The fitted set is treated as the tide; the unfitted constituents are zeroed in "
                           "prediction rather than carried as uncertain."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.40, freshness=0.35, uniqueness=0.62, g2_strength=0.65, duality_clarity=0.55,
            notes="INFERENCE: UTide's constituent-set fitting is sourced; the forecast-error-budget reading is the TPC framing.",
        ),
        TPCInstance(
            id="HEALPIX_SUBPIXEL",
            realm="astrophysics",
            name="HEALPix pixelization zeroes sub-pixel variation",
            source="Gorski et al. 2005, Astrophysical J. (HEALPix)",
            source_date="2005",
            omission_kind="discretization",
            omitted="Sub-pixel sky variation within each HEALPix pixel",
            zero_treatment="Pixel values used in power-spectrum estimation as if uniform within the pixel; pixel-window treated as the full correction",
            known_fact=("HEALPix discretizes the sphere into equal-area pixels (Gorski et al. 2005); "
                        "sub-pixel structure is averaged away by construction."),
            gap_statement=("Discretization zeroes intra-pixel gradients, then spectra are estimated as if the "
                           "pixel value were a point measurement."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.30, freshness=0.30, uniqueness=0.58, g2_strength=0.60, duality_clarity=0.50,
            notes="Weakest real instance; kept to show the gate floor. Likely PENALIZED.",
        ),
        TPCInstance(
            id="LIGO_TEMPLATE_MISMATCH",
            realm="astrophysics",
            name="GW template-bank best match treated as the signal",
            source="Usman et al. 2016, Classical & Quantum Gravity (PyCBC search)",
            source_date="2016",
            omission_kind="discretization",
            omitted="Off-bank waveform distance (the true signal is never exactly on the discrete bank)",
            zero_treatment="Detection statistic and parameter estimates reported at the best-match template; bank discreteness treated as zero error",
            known_fact=("PyCBC uses a discrete template bank with a minimal-match criterion (Usman et al. 2016); "
                        "no real signal lies exactly on a bank template."),
            gap_statement=("The bank discretizes waveform space; the analysis proceeds as if the best template "
                           "were the signal -- the off-bank distance is zeroed."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.40, freshness=0.40, uniqueness=0.64, g2_strength=0.55, duality_clarity=0.60,
            notes="INFERENCE: the bank/minimal-match machinery is sourced; the 'treated as zero error' reading is the TPC framing.",
        ),
        TPCInstance(
            id="BASEL_BUCKETING",
            realm="finance",
            name="Basel risk-weight buckets zero within-bucket variation",
            source="BIS Basel III framework (bis.org), standardized approach risk weights",
            source_date="2017",
            omission_kind="bucketing",
            omitted="Within-bucket exposure heterogeneity (all exposures in a band share one weight)",
            zero_treatment="Capital requirements computed as if every exposure in a bucket carried exactly the bucket weight; intra-bucket risk differences treated as zero",
            known_fact=("The Basel standardized approach assigns fixed risk weights to exposure buckets (BIS). "
                        "Bucketing is public regulatory machinery, not a model secret."),
            gap_statement=("Regulatory capital is computed on bucketed weights as if measured; the zeroed "
                           "within-bucket variation privileges the bucketed balance sheet."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.85, freshness=0.45, uniqueness=0.66, g2_strength=0.80, duality_clarity=0.70,
            notes="",
        ),
        TPCInstance(
            id="ANOVA_NO_INTERACTION",
            realm="statistics",
            name="Main-effects ANOVA without interactions treats them as zero",
            source="Gelman 2005, Ann. Statistics (Analysis of variance -- why it is more important than ever)",
            source_date="2005",
            omission_kind="dropping",
            omitted="Interaction terms not included in the ANOVA model",
            zero_treatment="Main effects interpreted as if interactions were measured-absent; tables report effects without interaction uncertainty",
            known_fact=("Gelman 2005 argues ANOVA remains central and interactions are routinely under-modeled; "
                        "omitted interactions bias main-effect interpretation."),
            gap_statement=("The un-modeled interactions are zeroed by model choice, then main effects are read "
                           "as if the zeroing were empirical."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.60, freshness=0.30, uniqueness=0.60, g2_strength=0.70, duality_clarity=0.65,
            notes="",
        ),
        TPCInstance(
            id="LEAMER_SPEC_SEARCH",
            realm="econometrics",
            name="Specification searching drops variables until results please",
            source="Leamer 1983, American Economic Review (Let's take the con out of econometrics)",
            source_date="1983",
            omission_kind="dropping",
            omitted="Variables dropped across the unreported specification search",
            zero_treatment="The reported specification is presented as if the dropped variables were known-irrelevant; search path unreported",
            known_fact=("Leamer 1983 is the canonical statement of specification-search bias in econometrics; "
                        "reported models hide the search that selected them."),
            gap_statement=("The search drops variables, then the surviving specification is treated as pre-specified -- "
                           "the dropped variables' effects are zeroed by the search, not by data."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.75, freshness=0.25, uniqueness=0.62, g2_strength=0.75, duality_clarity=0.75,
            notes="",
        ),
        TPCInstance(
            id="ECMWF_SPECTRAL_TRUNC",
            realm="atmospheric science",
            name="NWP spectral truncation zeroes sub-grid modes in resolved dynamics",
            source="ECMWF IFS documentation (ecmwf.int), spectral truncation",
            source_date="2024",
            omission_kind="truncation",
            omitted="Spherical-harmonic modes beyond the truncation wavenumber",
            zero_treatment="Resolved dynamics integrated as if truncated modes carry no energy; parameterizations stand in for the zeroed scales",
            known_fact=("Operational NWP integrates the primitive equations at finite spectral truncation (ECMWF IFS docs); "
                        "sub-grid processes are parameterized, not resolved."),
            gap_statement=("The truncation zeroes small-scale modes in the resolved dynamics; the parameterized "
                           "stand-in is treated as a measurement of those scales."),
            omission_by_truncation=True, treated_as_measured_zero=True, conclusion_affected=True,
            prior_class_overlap="",
            consequence=0.55, freshness=0.60, uniqueness=0.64, g2_strength=0.65, duality_clarity=0.60,
            notes="INFERENCE: truncation + parameterization are documented; the 'stand-in as measurement' reading is the TPC framing.",
        ),
        # ---- Controls ----
        TPCInstance(
            id="SYMMETRY_ZERO_CONTROL",
            realm="physics",
            name="CONTROL: symmetry-forbidden coefficient set to zero by physical law",
            source="Selection rules, e.g., Griffiths, Introduction to Quantum Mechanics (Pearson)",
            source_date="2018",
            omission_kind="physical_law",
            omitted="A transition amplitude forbidden by symmetry",
            zero_treatment="n/a -- control",
            known_fact="Selection rules set amplitudes to zero by conservation law, not by truncation.",
            gap_statement="n/a -- control: G1 must fail (omission by physical law, direction NONE).",
            omission_by_truncation=False, treated_as_measured_zero=False, conclusion_affected=False,
            prior_class_overlap="",
            consequence=0.0, freshness=0.2, uniqueness=0.2, g2_strength=0.0, duality_clarity=0.0,
            notes="CONTROL. Expects PENALIZED with G1 failed: zero by law is measured-by-theory (direction NONE), not TPC.",
        ),
        TPCInstance(
            id="PPC_DARK_DIMENSION",
            realm="space",
            name="CONTROL: dark-dimension DE x DM coupling (PPC primary)",
            source="PPC primary 2026-09-08",
            source_date="2026-09-08",
            omission_kind="phantom_dof",
            omitted="n/a -- phantom DOF added, not removed",
            zero_treatment="n/a -- control",
            known_fact="PPC primary. Extra unobservable DOF coupling two TAC objects.",
            gap_statement="n/a -- PPC owns this; dual-direction test must KILL it.",
            omission_by_truncation=False, treated_as_measured_zero=False, conclusion_affected=False,
            prior_class_overlap="PPC",
            consequence=0.2, freshness=0.8, uniqueness=0.2, g2_strength=0.0, duality_clarity=0.0,
            notes="CONTROL. Expects KILLED via G4: +DOF is PPC, the dual.",
        ),
        TPCInstance(
            id="UCC_KATUS_CONTROL",
            realm="land",
            name="CONTROL: Katus shortfall (UCC primary)",
            source="UCC primary 2026-09-10",
            source_date="2026-09-10",
            omission_kind="dropping",
            omitted="n/a -- control",
            zero_treatment="n/a -- control",
            known_fact="UCC primary. Entity without identifier cannot mint a death record.",
            gap_statement="n/a -- UCC owns this; archive subtraction must KILL it.",
            omission_by_truncation=False, treated_as_measured_zero=False, conclusion_affected=False,
            prior_class_overlap="UCC",
            consequence=0.2, freshness=0.9, uniqueness=0.2, g2_strength=0.0, duality_clarity=0.0,
            notes="CONTROL. Expects KILLED via G5.",
        ),
    ]
